# Site settings
title: Leo Cai
description: Software Engineer @ AWS Redshift
author: Leo Cai
url: "http://leocai.me"  # 暂时使用 http

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Theme settings
theme: minima  # 使用最简单的主题

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock

